# Generated by Django 5.2.7 on 2025-10-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(db_column='item_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('owner', models.CharField(default='Barangay Kauswagan', max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=20)),
            ],
            options={
                'db_table': 'core_item',
            },
        ),
    ]
