# Generated by Django 5.2.7 on 2025-10-27 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userborrower',
            name='borrower_status',
            field=models.CharField(default='Good', max_length=10),
        ),
        migrations.AddField(
            model_name='userborrower',
            name='late_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in use', 'In Use'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('On Time', 'On Time'), ('Late', 'Late Return'), ('Not Returned', 'Not Returned')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservation')),
                ('userborrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userborrower')),
            ],
        ),
    ]
