# Generated by Django 5.2.7 on 2025-10-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='T000000', max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('letter_image', models.ImageField(upload_to='reservation_letters/')),
                ('valid_id_image', models.ImageField(upload_to='reservation_ids/')),
                ('message', models.TextField()),
                ('contact', models.CharField(default='N/A', max_length=11)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('date_receive', models.DateTimeField(blank=True, null=True)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.item')),
                ('userborrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userborrower')),
            ],
        ),
    ]
