# Generated by Django 5.2.7 on 2025-10-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10),
        ),
    ]
