# Generated by Django 5.2.7 on 2025-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contact',
            field=models.CharField(blank=True, default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='letter_image',
            field=models.ImageField(blank=True, null=True, upload_to='reservation_letters/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='valid_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='reservation_ids/'),
        ),
    ]
