# Generated by Django 5.2.7 on 2025-11-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('admin_borrowed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_quantity', to='core.item')),
            ],
            options={
                'unique_together': {('item', 'date')},
            },
        ),
    ]
