# Generated by Django 5.2.7 on 2025-11-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminborrow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminquantity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='adminquantity',
            name='item',
        ),
        migrations.DeleteModel(
            name='AdminBorrow',
        ),
        migrations.DeleteModel(
            name='AdminQuantity',
        ),
    ]
