# Generated by Django 5.2.7 on 2025-11-18 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_adminquantity_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('return_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_borrows', to='core.item')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
