# Generated by Django 5.2.7 on 2025-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adminborrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='report_type',
            field=models.CharField(choices=[('Damage', 'Damage'), ('Loss', 'Loss')], default='Damage', max_length=20),
        ),
    ]
