# Generated by Django 5.2.7 on 2025-11-21 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_damagereport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='core.reservation'),
        ),
    ]
