# Generated by Django 5.2.7 on 2025-11-21 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_damagereport_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
    ]
